# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#     environment:
#       - ENV=development
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M